
CREATE TABLE info (id INT PRIMARY KEY AUTO_INCREMENT,
 login VARCHAR(30) NOT NULL UNIQUE,
senha VARCHAR(30) NOT NULL UNIQUE,
nome VARCHAR(200) NOT NULL UNIQUE,
email VARCHAR(100) UNIQUE NOT NULL,
cpf CHAR(11) NOT NULL UNIQUE,
rg CHAR(8) NOT NULL UNIQUE, 
idade INT(3),
nomePai VARCHAR(200),
nomeMao VARCHAR(200),
aniversário VARCHAR(10));